title: Dániel Varga
description: A showcase of my data engineering projects and certifications.
author: Dániel Varga
theme: minima
url: "https://danielv089.github.io" # your GitHub Pages URL
markdown: kramdown
