title: "Dániel Varga"
description: "Data Engineer Portfolio"
author: "Dániel Varga"
url: "https://danielv089.github.io"
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

