title: Dániel Varga
description: Data Engineering and Analytics projects
theme: jekyll-theme-minimal


url: "https://danielv089.github.io"
baseurl: ""

nav_links:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: About
    url: /about/
